import {
  Activity,
  CalendarCheck,
  HeartPulse,
  TrendingUp,
  UsersRound,
} from "lucide-react";

import type { Appointment, Conversation, MedicalEvent, Patient, Stat } from "@/types";

export const stats: Stat[] = [
  { label: "Pacientes Activos", value: "2.418", change: "+12,4%", tone: "blue", icon: UsersRound },
  { label: "Citas Hoy", value: "38", change: "+8", tone: "emerald", icon: CalendarCheck },
  { label: "Alertas Clínicas", value: "14", change: "-5,2%", tone: "amber", icon: HeartPulse },
  { label: "Eficiencia IA", value: "94%", change: "+3,1%", tone: "rose", icon: TrendingUp },
];

export const patients: Patient[] = [
  {
    id: "P-1024",
    name: "Camila Torres",
    email: "camila.torres@example.com",
    phone: "+593 98 421 7731",
    age: 42,
    gender: "Femenino",
    bloodType: "O+",
    condition: "Hipertensión controlada",
    risk: "Medio",
    status: "Seguimiento",
    lastVisit: "2026-05-04",
    nextVisit: "2026-05-18",
    doctor: "Dra. Valeria Ríos",
  },
  {
    id: "P-1025",
    name: "Andrés Molina",
    email: "andres.molina@example.com",
    phone: "+593 99 147 5021",
    age: 58,
    gender: "Masculino",
    bloodType: "A-",
    condition: "Diabetes tipo 2",
    risk: "Alto",
    status: "Crítico",
    lastVisit: "2026-05-08",
    nextVisit: "2026-05-11",
    doctor: "Dr. Mateo Herrera",
  },
  {
    id: "P-1026",
    name: "Lucía Zambrano",
    email: "lucia.zambrano@example.com",
    phone: "+593 97 804 2290",
    age: 31,
    gender: "Femenino",
    bloodType: "B+",
    condition: "Control prenatal",
    risk: "Bajo",
    status: "Activo",
    lastVisit: "2026-04-30",
    nextVisit: "2026-05-20",
    doctor: "Dra. Ana Beltrán",
  },
  {
    id: "P-1027",
    name: "Javier Cedeño",
    email: "javier.cedeno@example.com",
    phone: "+593 96 322 7719",
    age: 47,
    gender: "Masculino",
    bloodType: "AB+",
    condition: "Rehabilitación cardiaca",
    risk: "Medio",
    status: "Seguimiento",
    lastVisit: "2026-05-02",
    nextVisit: "2026-05-16",
    doctor: "Dr. Sebastián Núñez",
  },
  {
    id: "P-1028",
    name: "María Salazar",
    email: "maria.salazar@example.com",
    phone: "+593 98 011 8842",
    age: 64,
    gender: "Femenino",
    bloodType: "O-",
    condition: "Artritis reumatoide",
    risk: "Medio",
    status: "Activo",
    lastVisit: "2026-04-25",
    nextVisit: "2026-05-21",
    doctor: "Dra. Valeria Ríos",
  },
];

export const appointments: Appointment[] = [
  {
    id: "A-7441",
    patient: "Andrés Molina",
    doctor: "Dr. Mateo Herrera",
    specialty: "Endocrinología",
    date: "2026-05-10",
    time: "09:30",
    mode: "Presencial",
    status: "Confirmada",
  },
  {
    id: "A-7442",
    patient: "Camila Torres",
    doctor: "Dra. Valeria Ríos",
    specialty: "Cardiología",
    date: "2026-05-10",
    time: "11:00",
    mode: "Telemedicina",
    status: "Pendiente",
  },
  {
    id: "A-7443",
    patient: "Lucía Zambrano",
    doctor: "Dra. Ana Beltrán",
    specialty: "Ginecología",
    date: "2026-05-11",
    time: "08:45",
    mode: "Presencial",
    status: "Confirmada",
  },
  {
    id: "A-7444",
    patient: "Javier Cedeño",
    doctor: "Dr. Sebastián Núñez",
    specialty: "Rehabilitación",
    date: "2026-05-12",
    time: "15:20",
    mode: "Presencial",
    status: "Completada",
  },
];

export const medicalTimeline: MedicalEvent[] = [
  {
    id: "M-901",
    date: "2026-05-08",
    title: "Ajuste de Metformina",
    doctor: "Dr. Mateo Herrera",
    type: "Medicación",
    description: "Glucosa en ayunas elevada. Se ajusta dosis nocturna y se agenda control en 72 horas.",
    tags: ["Diabetes", "Farmacología", "Seguimiento"],
  },
  {
    id: "M-902",
    date: "2026-05-04",
    title: "Presión Arterial Estable",
    doctor: "Dra. Valeria Ríos",
    type: "Diagnóstico",
    description: "Lecturas promedio dentro de objetivo. Mantener dieta baja en sodio y caminatas diarias.",
    tags: ["Cardiología", "Prevención"],
  },
  {
    id: "M-903",
    date: "2026-04-29",
    title: "Plan de Rehabilitación",
    doctor: "Dr. Sebastián Núñez",
    type: "Tratamiento",
    description: "Se inicia bloque de movilidad progresiva, control de frecuencia cardiaca y educación familiar.",
    tags: ["Rehabilitación", "Cardio"],
  },
  {
    id: "M-904",
    date: "2026-04-21",
    title: "Nota de Enfermería",
    doctor: "Lic. Paola Vera",
    type: "Nota",
    description: "Paciente orientado, hidratado, sin signos de alarma reportados durante seguimiento remoto.",
    tags: ["Enfermería", "Telemonitoreo"],
  },
];

export const conversations: Conversation[] = [
  {
    id: "C-001",
    title: "Riesgo metabólico",
    summary: "Análisis de glucosa, peso y adherencia terapéutica.",
    updatedAt: "2026-05-10T08:30:00",
  },
  {
    id: "C-002",
    title: "Priorización de citas",
    summary: "Pacientes con mayor urgencia para esta semana.",
    updatedAt: "2026-05-09T17:45:00",
  },
  {
    id: "C-003",
    title: "Resumen clínico",
    summary: "Informe breve para junta médica de cardiología.",
    updatedAt: "2026-05-07T13:20:00",
  },
];

export const activityFeed = [
  { icon: Activity, title: "IA generó 6 recomendaciones", detail: "Cohorte diabetes tipo 2", time: "Hace 12 min" },
  { icon: CalendarCheck, title: "Cita confirmada", detail: "Camila Torres con Cardiología", time: "Hace 28 min" },
  { icon: HeartPulse, title: "Alerta clínica resuelta", detail: "Presión arterial estabilizada", time: "Hace 1 h" },
];
